# Entropy, Information gain , Gini entropy

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import math

In [3]:
# Example dataset
# Let's say we have a dataset with two classes A ana B
# Suppose in a dataset of 10 elements, 4 are of class A and 6 are of class B

# Number of elements ion each class
n_A = 4
n_B = 6
total = n_A + n_B

In [4]:
# Let's calculate the proportion
p_A = n_A / total
p_B = n_B / total

# print the proportions
print('Proportion of A : ', p_A)
print('Proportion of B : ', p_B)

Proportion of A :  0.4
Proportion of B :  0.6

In [5]:
# Entropy Calculated
# Entropy is a measure of uncertainiy
entropy = -p_A * math.log2(p_A) - p_B * math.log2(p_B)
print('Entropy : ', entropy)

Entropy :  0.9709505944546686

In [6]:
# Gini impurity
# Gini impurity is a measure of misclassification
gini = 1 - p_A**2 - p_B**2
print('Gini Impurity : ', gini)

Gini Impurity :  0.48

In [7]:
# Information Gain
# Assuming a split on some features divide the dataset into two subsrts
# Subsrt 1:2 elements of A, 3 of B
# Subset 2 : 2 elements of A, 3 of B
# entropy and size for each subset
n_1_A, n_1_B = 2,3
n_2_A, n_2_B = 2,3

p_1_A = n_1_A / (n_1_A + n_1_B)
p_1_B = n_1_B / (n_1_A + n_1_B)
entropy_1 = -p_1_A * math.log2(p_1_A) - p_1_B * math.log2(p_1_B) if p_1_A and p_1_B else 0

p_2_A = n_2_A / (n_2_A + n_2_B)
p_2_B = n_2_B / (n_2_A + n_2_B)
entropy_2 = -p_2_A * math.log2(p_2_A) - p_2_B * math.log2(p_2_B) if p_2_A and p_2_B else 0

# claculate information gain
info_gain = entropy - ((n_1_A + n_1_B) / total * entropy_1 + (n_2_A + n_2_B) / total * entropy_2)
print('Information gain : ',info_gain)

Information gain :  0.0

# Decision tree

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [11]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
# drop deck columns
df.drop('deck',axis=1, inplace=True)

# impute missing values of age and fare using median
imputer = SimpleImputer(strategy='median')
df[['age','fare']] = imputer.fit_transform(df[['age','fare']])

# impute missing values of embark_town and embarked
imputer = SimpleImputer(strategy='most_frequent')
df[['embark_town', 'embarked']] = imputer.fit_transform(df[['embark_town','embarked']])

In [18]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [20]:
# Encode the categorical and object variables using for loop and labelencoder
le = LabelEncoder()
for col in df.select_dtypes(include=['category', 'object']):
    df[col] = le.fit_transform(df[col])

In [21]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [22]:
# split the data in X and y
X = df.drop('survived', axis=1)
y = df['survived']

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [24]:
# create and train the model with prediction
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

# predict the model
y_pred = model.predict(X_test)

In [28]:
# Evaluate the model
print('Confusion Matrix : \n', confusion_matrix(y_test,y_pred))
print('\nClassification Report : \n', classification_report(y_test,y_pred))

Confusion Matrix :
 [[105   0]
 [  0  74]]

Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        74

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179

In [30]:
# save the decision tree classifier
from sklearn.tree import export_graphviz

export_graphviz(
    model,
    out_file='Decision_Tree.dot',
    feature_names=X.columns,
    filled=True,
    rounded=True
)

In [34]:
!pip install graphviz

Defaulting to user installation because normal site-packages is not writeable

WARNING: Ignoring invalid distribution ~umpy (C:\Users\2005a\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\2005a\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\2005a\AppData\Roaming\Python\Python313\site-packages)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting graphviz
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz
Successfully installed graphviz-0.21