In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# Encode features which are categoorical or object usiong for loop
le = LabelEncoder()
for i in df.columns:
    if df[i].dtype == 'object' or df[i].dtype == 'category':
        df[i] = le.fit_transform(df[i])

df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [6]:
# Split the data into X and y for classification
X = df.drop('sex', axis=1)
y  = df['sex']

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [8]:
# Create train and predict the model
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [11]:
# Evaluate the model
print('Accuracy Score : ', accuracy_score(y_test,y_pred))
print('\nConfusion Matrix :\n ', confusion_matrix(y_test,y_pred))
print('\nClassification Report : \n', classification_report(y_test,y_pred))

Accuracy Score :  0.6326530612244898

Confusion Matrix :
  [[ 7 12]
 [ 6 24]]

Classification Report :
               precision    recall  f1-score   support

           0       0.54      0.37      0.44        19
           1       0.67      0.80      0.73        30

    accuracy                           0.63        49
   macro avg       0.60      0.58      0.58        49
weighted avg       0.62      0.63      0.61        49

In [12]:
# Use Random Forests for Regression task
X= df.drop('tip', axis=1)
y=df['tip']

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [16]:
# Create train and predict the model
model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [17]:
print('MSE :', mean_squared_error(y_test,y_pred))
print('MAE : ', mean_absolute_error(y_test,y_pred))
print('R2 score : ', r2_score(y_test,y_pred))
print('RMSE : ', np.sqrt(mean_squared_error(y_test,y_pred)))

MSE : 0.9496955984183694
MAE :  0.7704663265306128
R2 score :  0.2402261043743361
RMSE :  0.9745232672534655